# Per default the schema of arbitrary context values of a condition cannot be
# typed. Conditions that need translatability or other features of the config
# system must specify their context value schema explicitly, see examples below.
social_automation.condition.context_values.*:
  type: ignore
  label: Context values

social_automation.condition.context_values.social_automation_entity_is_new:
  type: mapping
  label: Entity is new context values
  mapping:
    entity:
      type: string
